caicloud/nirvana

- .travis.yml
- README.md
> feat(build): add landscape/goreport/coverall status badge

- README.md
> fix(*): remove links to private repos

- router/router_test.go
- Add more tests for router.
- Refine some code when adding tests.
Fix https://github.com/caicloud/nirvana/issues/13
@kdada @ddysher
> feat(router): add tests for router

- config.json
update gometalinter config to ignore vendor files
we shall not lint `vendor` files
> fix(lint): Update config.json

- LICENSE
- cmd/license/apache.go
- doc.go
- errors/errors.go
- router/basic.go
- router/executor.go
- router/path.go
- router/regexp.go
- router/router.go
- router/router_test.go
- router/string.go
> add License and tool

- cli/README.md
> docs: add cli README

- LICENSE
- Makefile
- boilerplate/boilerplate.go.txt
- cmd/license/apache.go
- correct license content
- read license header from boilerplate
> fix(license): correct License content

- validator/README.md
Add validator pkg README.md
There is no README.md for validator pkg now.
> feat(validator): add validator readme

- errors/doc.go
- errors/errors.go
- errors/errors_test.go
- errors/preset.go
Add errors pkg.
Currently, errors is not ready to use.
This PR will make a standard error which should be used in future.
> feat(errors): add errors

- .travis.yml
1. add `--deadline=300s` for `gometalinter`
@Jimexist @ddysher
> chore(ci): add deadline of gometalinter

- cli/config_test.go
- config.json
- web/default.go
- web/web.go
- web/web_test.go
add `gosimple` to `gometalinter`
> feat(lint): add gosimple

- examples/swapi/cmd/swapi/main.go
- examples/swapi/pkg/api/people/get_by_id.go
- examples/swapi/pkg/api/people/list.go
- examples/swapi/pkg/api/people/people.go
- examples/swapi/pkg/api/people/sort_by_id.go
- examples/swapi/pkg/api/v1/v1.go
- examples/swapi/pkg/loader/model_loader.go
add query by id and list by id example part
> feat(example): list by id and query by id

- plugins/tracing/tracing.go
> fix(tracing): check errors

- OWNERS
- cli/OWNERS
- cmd/openapi-gen/OWNERS
- definition/OWNERS
- docs/OWNERS
- errors/OWNERS
- hack/OWNERS
- log/OWNERS
- operators/converter/OWNERS
- operators/validator/OWNERS
- plugins/metrics/OWNERS
- plugins/profiling/OWNERS
- plugins/tracing/OWNERS
- service/OWNERS
- utils/openapi/OWNERS
Add owners file for directories. 
**Why we need it**
Caicloud bot needs it to manage the repo.
**Release note**
```release-note
NONE
```
> chore(owners): set up owners for directories

- service/builder.go
I move definition warning log to apposite position.
/assign @yejiayu 
/area framework
/kind enhancement
/priority p1
```release-note
NONE
```
> fix(service): move definition warning log to apposite position

- service/builder_test.go
- service/executor.go
- service/source.go
- service/source_test.go
- Add `default` source tag. 
- All basic types of params have a default value.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
/assign @kdada 
```release-note
NONE
```
> feat(source): add default tag and set default value

- service/builder.go
- service/content.go
Remove useless codes in service builder and fix a typo in passing.
/assign @yejiayu 
```release-note
NONE
```
> Remove useless codes in builder

- plugins/tracing/tracing.go
Add `StartSpanFromContext` function
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
```release-note
NONE
```
> feat(tracing): Add `StartSpanFromContext`

- README.md
- doc(readme): add get started section into README.md
```release-note
Update README.md
```
> doc(readme): add get started section into README.md

- operators/validator/validator.go
- operators/validator/validator_test.go
Make a user friendly validation errors.
Fixes #126
/cc @ddysher @kdada 
```release-note
NONE
```
> feat(validator): refine error message

- cmd/openapi-gen/generators/openapi.go
- cmd/openapi-gen/generators/openapi_test.go
Fixes #122 
/cc @ddysher 
```release-note
NONE
```
> fix(openapi): fix unused import

- examples/instrumentation/main.go
- plugins/metrics/metrics.go
for https://github.com/caicloud/nirvana/issues/121
```release-note
NONE
```
> feat(metrics): add default metrics for http requests

- README.md
- examples/getting-started/metrics/echo.go
Update README for default metrics
Fixes #
/cc @kdada @caitong93 
```release-note
NONE
```
> docs(readme): update metrics readme

- plugins/profiling/profiling.go
- plugins/tracing/tracing.go
Fix type in plugins
Fixes #
/cc @kdada 
```release-note
NONE
```
> fix(plugins): fix typo

- README.md
Fix wrong logo image
Fixes #
/cc @kdada @walktall 
```release-note
NONE
```
> fix(logo): update logo

- README.md
- feat(readme): add details for API
Fixes #
```release-note
NONE
```
> feat(readme): add details for API

- .pre-commit-config.yaml
Fixes #
/cc @kdada
```release-note
adding pre-commit config
```
> adding pre-commit config

- plugins/metrics/metrics.go
- plugins/profiling/profiling.go
- service/utils.go
Fixes #
/cc @kdada
```release-note
warp 👉 wrap
```
> warp 👉 wrap

- README.md
Update README
Fixes #
/cc @kdada 
```release-note
NONE
```
> docs(readme): update readme for user guide

- service/utils.go
Fixes #
/cc @kdada
```release-note
NONE
```
> feat(error): adding some more detailed error descriptions

- examples/getting-started/validator/echo.go
- operators/validator/validator.go
- operators/validator/validator_test.go
Update validator.
Fixes #
/cc @ddysher @kdada 
```release-note
NONE
```
> feat(validator): refine custom validator and add example

- README.md
Add validation user guide in README
Fixes #
/cc @kdada @walktall 
Depends on https://github.com/caicloud/nirvana/pull/150
```release-note
NONE
```
> docs(README): add validation readme

- README.md
Update README following #157
Fixes #
/cc @caitong93 @kdada 
```release-note
NONE
```
> docs(readme): update metrics section

- README.md
- docs/proposals/framework.md
- docs/proposals/kickoff.md
Fixes #
/cc @kdada 
```release-note
NONE
```
> docs(proposals): add kickoff and framework proposal

- service/router/router_test.go
Add ref links for test code borrowed from go-chi
/cc @ddysher 
```release-note
NONE
```
> chore(ref): ref for tests from go-chi

- Gopkg.lock
- Gopkg.toml
- config/center.go
- config/config.go
- nirvana.go
- plugins/metrics/metrics.go
- plugins/profiling/profiling.go
- vendor/github.com/spf13/pflag/count.go
- vendor/github.com/spf13/pflag/count_test.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/flag_test.go
- vendor/github.com/spf13/pflag/int16.go
- chore(vendor): update vendor
- feat(config): add nirvana command
- feat(plugins): add plugin options
Fixes #
```release-note
Add nirvana config
Add nirvana command
Add plugin options
```
>  feat(config): add nirvana config

- config/center_test.go
- config/config.go
- config/config_test.go
- feat(config): add tests
Fixes #161
/area test
```release-note
Add tests for config
```
> feat(config): add tests

- examples/api-basic/api/v1/install.go
- examples/api-basic/api/v2/install.go
- examples/api-basic/main.go
- examples/getting-started/basics/echo.go
- examples/getting-started/metrics/echo.go
- examples/getting-started/openapi/echo.go
- examples/getting-started/validator/echo.go
- examples/instrumentation/main.go
- examples/stream/api/v1/install.go
- examples/stream/main.go
- examples/tracing/main.go
- feat(examples): start with config.Command instead of nirvana.Server
Fixes #163 
```release-note
NONE
```
> feat(examples): start with config.Command instead of nirvana.Server

- README.md
- cmd/openapi-gen/generators/openapi_test.go
- cmd/openapi-gen/generators/tag.go
- cmd/openapi-gen/generators/tag_test.go
- examples/getting-started/openapi/pkg/api/types.go
- examples/openapi/README.md
- examples/openapi/pkg/api/v1/doc.go
Fixes #141 
/cc @ddysher 
```release-note
NONE
```
> feat(openapi): change openapi tag from caicloud to nirvana

- README.md
Describe plugins in README.md.
Fixes #
/cc @ddysher 
```release-note
Describe plugins in README.md.
```
> feat(readme): update plugin docs

- README.md
ref: https://github.com/caicloud/nirvana/pull/174
Fixes #
/cc @kdada 
```release-note
NONE
```
> docs(README): refine plugin README

- README.md
- config/config.go
- config/config_test.go
- examples/tracing/main.go
- nirvana.go
Remove parameters of nirvana.NewDefaultConfig().
Fixes #
/cc @ddysher 
```release-note
Remove parameters of nirvana.NewDefaultConfig()
```
> feat(nirvana): remove parameters of nirvana.NewDefaultConfig()

- README.md
Update Configurer docs
Fixes #
/cc @ddysher 
```release-note
NONE
```
> docs(readme): update Configurer docs

- config/config.go
- nirvana.go
- plugins/tracing/tracing.go
Export `server.Builder`, you can get service builder now.
Service builder can build HTTP services. The services can be used in another special server or test.
Fixes #
/cc @yejiayu 
/cc @ddysher 
```release-note
NONE
```
> feat(server): allow to get service builder from nirvana server

- nirvana.go
Fixes #
/cc @kdada 
```release-note
NONE
```
> fix(nirvana): export Server.Builder

- service/builder_test.go
- service/context.go
- service/executor.go
Inspector will set abstract path into HTTP context now. Middlewares and Handlers can get abstract path from context.
Fixes #
/cc @ddysher 
/cc @yejiayu 
```release-note
NONE
```
> feat(service): save abstract path into http context

- examples/tracing/main.go
- plugins/tracing/clients/http/http.go
- plugins/tracing/clients/http/http_test.go
- plugins/tracing/middleware/middleware.go
- plugins/tracing/middleware/middleware_test.go
- plugins/tracing/utils/utils.go
Fixes #
/cc @ddysher @kdada 
```release-note
NONE
```
> refactor(tracing): change dir

- cmd/openapi-gen/builder/openapi.go
- cmd/openapi-gen/builder/openapi_test.go
Fixes #137 
/cc @ddysher 
```release-note
NONE
```
> fix(openapi): fix path item overriding problem

- examples/tracing/main.go
- plugins/tracing/tracing.go
- plugins/tracing/tracing_test.go
Fixes #
```release-note
NONE
```
> feat(tracing): Add options

- examples/tracing-basic/main.go
- examples/tracing/README.md
- examples/tracing/services/api/server.go
- examples/tracing/services/config/server.go
- examples/tracing/services/models/application.go
- examples/tracing/services/store/application.go
- examples/tracing/services/store/config.go
Add tracing example
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
```release-note
NONE
```
>  example(tracing): Add tracing example

- service/filter.go
Fixes #
/cc @kdada
```release-note
Treat Content-Length "" and "0" equally
```
> fix(service): treat Content-Length "" and "0" equally

- service/content.go
- service/content_test.go
- service/executor_test.go
Fixes #
```release-note
feat(service): add more converter
```
> feat(service): add more converters

- service/source.go
Correct result of `AutoParameterGenerator.Generate`.
Fixes #
/cc @zoumo 
```release-note
Correct result of AutoParameterGenerator.Generate
```
> fix(service): correct result of AutoParameterGenerator.Generate

- service/content.go
return right pointer type
the old way got *interface{} not *bool or *int,
*interface{} can not be assigned to *bool or *int
Fixes #
```release-note
fix(converter): return right pointer type 
```
> fix(converter): return right pointer type

- config/hooks.go
Fix PreConfigure wrong call
Fixes #
```release-note
NONE
```
> fix(config): fix PreConfigure wrong call

- config/config.go
- config/config_test.go
- utils/printer/table.go
- utils/printer/table_test.go
Use table printer to format help message.
```
➜  testnirvana ./testnirvana --help
ConfigKey-ENV-Flag Mapping Table
Config Key                   ENV                          Flag                    Current Value
1  server.ip                    SERVER_IP                    --ip
2  server.metrics.namespace     SERVER_METRICS_NAMESPACE     --metrics-namespace
3  server.metrics.path          SERVER_METRICS_PATH          --metrics-path          /metrics
4  server.port                  SERVER_PORT                  --port                  8080
5  server.profiling.contention  SERVER_PROFILING_CONTENTION  --profiling-contention  false
6  server.profiling.path        SERVER_PROFILING_PATH        --profiling-path        /profiling
Usage:
server [flags]
Flags: …
```
>  feat(config): use table printer to format help message

- log/default.go
- log/log.go
- log/silent.go
- log/std.go
- plugins/logger/logger.go
Add logger plugin. Now log options can be modified by flags.
Fixes #
/cc @zoumo 
/cc @ddysher 
```release-note
NONE
```
> feat(logger): add logger plugin

- plugins/reqlog/reqlog.go
Add request logging plugin.
Default:
```
INFO  0330-15:29:46.837+08 reqlog.go:100 | GET 200 3 101.48506ms /echo?msg=xxx
```
| Value | Description |
| ------- | -------------- |
| GET | HTTP Method |
| 200 | Status Code |
| 3 | Response Body Length |
| 101.48506ms | Request Time Consuming |
| /echo?msg=xxx | URL |
Enable DoubleLog, SourceAddr, RequestID:
```
INFO  0330-15:31:16.777+08 reqlog.go:100 | GET /echo?msg=xxx HereIsRequestID 127.0.0.1:51262
INFO  0330-15:31:16.877+08 reqlog.go:100 | GET 200 3 100.447277ms /echo?msg=xxx HereIsRequestID 127.0.0.1:51262
```
| Value | Description |
| ------- | -------------- |
| HereIsRequestID | Request ID |
| 127.0.0.1:51262 | Source Addr |
Double log outputs two entries for every request.
**Which issue(s) …
> feat(reqlog): add request logging plugin

- service/executor.go
- service/executor_test.go
Fix wrong conflict definition check
Fixes #198
/cc @zjj2wry 
```release-note
NONE
```
> fix(service): fix wrong conflict definition check

- CONTRIBUTING.md
- ROADMAP.md
Add ROADMAP.md and CONTRIBUTING.md
Fixes #
/cc @ddysher 
```release-note
NONE
```
> feat(*): add ROADMAP.md and CONTRIBUTING.md

- .travis.yml
- cmd/openapi-gen/builder/openapi.go
Upgrade go version from `1.8` and `1.9` to `1.10.x`.
Fixes #202 
/cc @ddysher 
```release-note
NONE
```
> chore(travis): upgrade go version to latest

- plugins/tracing/hook.go
- plugins/tracing/tracing.go
- plugins/tracing/tracing_test.go
- feat(tracing): Add 'RequestHook'
Fixes #
/assign @kdada
/assign @ddysher
```release-note
NONE
```
> feat(tracing): add tracing hook

- nirvana.go
Support TLS
Fixes #
/cc @kdada
```release-note
NONE
```
> feat(nirvana): support TLS

- cmd/nirvana/api/api.go
- cmd/nirvana/buildutils/builder.go
- cmd/nirvana/client/client.go
- utils/api/analyzer.go
- utils/api/api.go
- utils/builder/builder.go
- utils/generators/golang/generator.go
- utils/project/config.go
This PR fixed two related bugs:
- API analyzer needs root path to find correct packages.
- Builder needs root path to generate temporary codes and build API definitions.
Rather than generates codes in system `tmp` directory, it generates codes into project and deletes it after building.  
I make this change because golang does not support to import packages from vendor.
Fixes #
Reference to #
```release-note
NONE
```
> fix(generators): correnct root path of api and builder

- service/utils.go
Fixes #200 
Reference to #
```release-note
NONE
```
> fix(service): change invalidConversion type to BadRequest

- config/config.go
Support TLS options
Fixes #
Reference to #
```release-note
NONE
```
> feat(config): support TLS options

- config/config.go
- plugins/healthcheck/healthz.go
- plugins/version/version.go
Add two small plugins.
Fixes #51 
Reference to #
```release-note
NONE
```
> feat(plugins): add version and health check plugins

- plugins/healthcheck/healthz.go
- plugins/metrics/metrics.go
- plugins/profiling/profiling.go
- plugins/reqlog/reqlog.go
- plugins/tracing/tracing.go
- plugins/version/version.go
Rename wapper to wrapper
Fixes #
Reference to #
/assign @zjj2wry 
```release-note
NONE
```
> fix(plugins): rename wapper to wrapper

- rest/rest.go
Save context into request. Then raw client and RoundTriper can extract info from the context.
Fixes #
Reference to #
```release-note
NONE
```
> feat(rest): save context into request

- cmd/nirvana/api/api.go
- cmd/nirvana/client/client.go
- cmd/nirvana/project/init.go
Move `/pkg/api` to `/pkg/apis`.
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
>  feat(cmd): move `/pkg/api` to `/pkg/apis`

- examples/instrumentation/main.go
- plugins/profiling/profiling.go
Remove profiling contention.
Fixes #
Reference to #
/cc @zjj2wry 
```release-note
NONE
```
> fix(profiling): remove contention

- service/handler.go
- service/utils.go
Support static file. 
Fixes #
Reference to #
/cc @zxq-bit 
```release-note
NONE
```
> feat(service): add helper functions to support static file server

- cmd/nirvana/client/client.go
- utils/api/types.go
- utils/generators/golang/generator.go
- utils/generators/golang/helper.go
- utils/generators/swagger/generator.go
This PR fixes several bugs about generators.
- Add conflict counter to record how many different types with same pkgPath and Name. (`utils/api/types.go`)
- This issue is from package `method`. `method` may creates a lot of functions with same pkgPath and Name.
- Correct inline struct generation in swagger (`utils/generators/swagger/generator.go`)
- Correct interface generation in swagger (`utils/generators/swagger/generator.go`)
- Only export type definitions which are from current project. (`utils/generators/golang/helper.go`)
- Types from standard libraries and third-party libraries are not generated to client packages.
Fixes #
Reference to #
**Special notes for your …
> fix(generators): correct conflicting types and fix two generators

- service/context.go
Remove empty strings from queries/headers/forms. This PR skips wrong conversions from converters.
Fixes #
Reference to #
/assign @zxq-bit 
```release-note
NONE
```
> fix(service): remove empty strings from queries/headers/forms

- utils/generators/swagger/generator.go
`nirvana api` did not generate schema for map type. This pr fixed it.
Fixes #
Reference to #
/cc @ddysher 
/cc @zjj2wry 
```release-note
NONE
```
> fix(openapi): correct api generation for map

- README.md
It's painful to read a readme more than a thousand lines of documentation without a **directory**
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> chore(docs): add directory of README.md

- cmd/nirvana/project/init.go
Makefile does not pass VERSION and COMMIT to Dockerfile. It causes `make container` can't set `version.Version` and `version.Commit`.
This PR fixed it. Also this PR add suffix `-dirty` to COMMIT if gittree is not clean.
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> fix(project): passthrough VERSION and COMMIT from Makefile to Dockerfile

- plugins/apidocs/OWNERS
- plugins/apidocs/apidocs.go
Add plugin apidocs to return swagger.json
Fixes #
Reference to #
/cc @liubog2008 
```release-note
Add plugin apidocs
```
> feat(apidocs): add plugin apidocs

- cmd/nirvana/project/init.go
- manuals/zh-hans/guides/project.md
add manual for go module support (#239)
modify GoMod field of initOptions to Pkgmgr (#239)
modify "--mod" argument in manual project.md (#239)
fixbug: miss log when the value of pkgmrg is invalid (#239)
add target mod-reset-vendor (#239)
This PR add `pkgmgr`(*package manager*) argument to `nirvana init` command. Currently, The additional argument has two valid values - `dep` or `mod` , corresponding to pkg manager dep and go module function respectively.
I finally replaced `--mod` with `--pkgmgr` instead of `--vendor`. In my opinion, it's semantically more appropriate.
Fixes #239
Reference to #
/assign @ddysher …
> feat(project): add go.mod template and '--package-manager' flag to support go modules

- cmd/nirvana/buildutils/builder.go
- utils/api/analyzer.go
- utils/api/comments.go
- utils/api/definitions.go
- utils/builder/builder.go
- utils/project/config.go
- utils/project/path.go
Are you meant to make it...
Fixes #
Reference to #
/cc @kdada 
```release-note
NONE
```
> chore(*): fix typos

- examples/getting-started/validator/echo.go
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> fix: correct the wrong method

- service/filter.go
- service/filter_test.go
This PR fix the issue in #246.
Fixes #246 
Reference to #
/cc @ddysher 
```release-note
NONE
```
> fix(service): fix the parser of accept types

- plugins/profiling/profiling.go
Plugin profiling is out of date. This PR add latest features of profiling from golang 1.11.
Fixes #244 
Reference to #
```release-note
NONE
```
> feat(profiling): add latest features of profiling from golang

- examples/api-basic/api/v2/app_test.go
- utils/unittest/unittest.go
Add helper functions for writing unit test.
Fixes #
Reference to #
/cc @kdada @ddysher 
```release-note
NONE
```
> feat: add tools for unit test

- cmd/nirvana/project/init.go
Signed-off-by: Ce Gao <gaoce@caicloud.io>
Support commit recognition in Ubuntu
Fix https://github.com/caicloud/nirvana/issues/252
```release-note
NONE
```
> init: Support the script in sh

- README.md
R.T
Fixes #
Reference to #
/cc @kdada 
```release-note
NONE
```
> chore: minor README update

- CONTRIBUTING.md
R.T
Fixes #
Reference to #
/cc @kdada 
```release-note
NONE
```
> chore: minor CONTRIBUTING update

- config.json
Remove megacheck from the config of gometalinter
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> chore(linter): remove megacheck from the config of gometalinter

- ROADMAP.md
Update roadmap
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> feat(roadmap): add roadmap for v0.3

- cmd/nirvana/api/api.go
Fixes #265
Reference to #
/cc @kdada @ddysher 
```release-note
NONE
```
> fix(#265): fix format for generated api json file

- service/builder.go
Use `EscapedPath()` instead of `Path` to support encoded URI in request path.
Fixes #275
Reference to #
/cc @kdada 
```release-note
NONE
```
> fix(#275): support encoded URI in request path

- config/config.go
fix bug: tls configure error:
defination here: 
```golang
// TLS returns a configurer to set certFile and keyFile in config.
func TLS(certFile, keyFile string) Configurer {
return func(c *Config) error {
c.certFile = certFile
c.keyFile = keyFile
return nil
}
}
```
but use TLS function here: 
```golang
// Configure configures nirvana config via current option.
func (p *Option) Configure(cfg *nirvana.Config) error {
cfg.Configure(
nirvana.IP(p.IP),
nirvana.Port(p.Port),
nirvana.TLS(p.Key, p.Cert),
)
return nil
}
```
here, nirvana.TLS set a transposed parameters
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> fix tls configure error

- OWNERS
- README.md
- definition/OWNERS
- errors/OWNERS
- hack/OWNERS
- log/OWNERS
- operators/converter/OWNERS
- operators/validator/OWNERS
- plugins/apidocs/OWNERS
- plugins/metrics/OWNERS
- plugins/profiling/OWNERS
- plugins/tracing/OWNERS
- service/OWNERS
RT
Fixes #
Reference to #
/cc @kdada @bbbmj 
```release-note
NONE
```
> Update README and remove nested OWNERS

- nirvana.go
- service/filter.go
refactor(*): fix typo and add comments and tweak
Fixes #
Reference to #
/cc @bbbmj 
```release-note
NONE
```
> refactor(*): fix typo and add comments and tweak

- utils/builder/builder.go
nirvana panic when i run `nirvana api --serve=":8081"` on windows.  
```shell
INFO  0927-13:54:53.799+08 api.go:87 | No packages are specified, defaults to pkg/apis
nirvana-generated573984343\main.go:20:37: non-hex character in escape sequence: s
nirvana-generated573984343\main.go:20:48: unknown escape sequence
FATAL 0927-13:55:06.890+08 api.go:61 | exit status 2
```
finally i find that APIBuilder.file func in `utils/builder` write wrong root path like `c:\some\directory` in generated `main.go`.  
this pr fixes the problem.  
but i think it only works in linux-based shell(like git-bash) on windows.
/cc @kdada 
```release-note
fix `nirvana api` command fail on windows.  
```
> fix: nirvana api cmd write wrong container root on windows.

- definition/helper.go
fix comment.
/cc @kdada 
```release-note
NONE
```
> fix: comments for helper.

- definition/definition.go
- service/builder.go
- utils/api/definitions.go
- utils/generators/swagger/generator.go
Fixes #300
Reference to #
/cc @iawia002 @kdada 
```release-note
feat(#300): support tags for generated API docs
```
> feat(#300): support tags for generated API docs

- nirvana.go
Fixes #305
Reference to #
/cc @iawia002 @kdada 
```release-note
NONE
```
> fix(#305): include pkg utils/api for projects' deps to generate api docs

- cmd/nirvana/api/api.go
Fixes #
Reference to #
/cc @supereagle @hezhizhen 
```release-note
NONE
```
> feat(api): switch to swagger-ui

- metrics/metrics.go
- middlewares/metrics/metrics.go
- plugins/metrics/metrics.go
- vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
- vendor/modules.txt
Added metric middleware that mimick the functionality of the `metrics` plugin. Unlike a plugin, middleware can be added only to a subset of the descriptors.
Fixes #
Reference to #
/cc @supereagle @iawia002 
```release-note
NONE
```
> feat(middleware): implemented metrics middleware

- utils/api/types.go
Handle struct fields separately to deal with nested structures which may cause infinite recursion when generating API docs, eg: 
```go
type Message struct {
ID      int                  `json:"id"`
Title   []string             `json:"title"`
Content [][]string           `json:"content"`
M1      *[]*[]*Message       `json:"m1"`
M2      *Message             `json:"m2"`
M3      map[*Message]Message `json:"m3"`
}
```
This will cause infinite recursion when nirvana trying to fetch the info of the field `M1`, `M2` and `M3`, after this change, the `Message` struct in `M1`, `M2` and `M3` will be treated as empty:
Reference to #297 
/cc …
> fix(utils): handle the nested element that may cause infinite recursion when generating API docs

- cmd/nirvana/api/api.go
After we support recursive definition in #319, I found some special structures will cause swagger-ui to report an error (data presentation is normal, just the web page keeps prompting for this error), eg:
```go
type T2 struct {
ID  int `json:"id"`
T21 *T2 `json:"t21"`
}
// Message describes a message entry.
type Message struct {
ID      int                  `json:"id"`
Title   []string             `json:"title"`
Content [][]string           `json:"content"`
T2      T2                   `json:"t2"`
}
```
After a period of time of debugging, I found out that this issue may be caused by swagger-client@3.9.0 (introduced in version 3.22.3), so this PR downgrades swagger-ui version to 3.22.2 and everything works correctly again.
I'll continue to look …
> chore(*): downgrade swagger-ui version to 3.22.2

- utils/api/types.go
In #319, the method of determining whether a field is a nested type is somehow problematic when dealing with the following struct:
```go
type Message struct {
ID      int                `json:"id"`
Title   []string           `json:"title"`
Content [][]string         `json:"content"`
T2      MessageT2          `json:"t2"`
}
```
The filed `T2` will be treated as a nested field (but it's not) cause `message.MessageT2` contains `message.Message`, this will cause nirvana to no longer process this field, and the document generated will lack information of this field.
Fixes #
Reference to #
/cc @hezhizhen @supereagle  …
> fix(utils): fix wrong judgment method for nested types

- utils/generators/swagger/generator.go
Fixes #
Reference to #
/cc @iawia002 
```release-note
NONE
```
> fix(api-doc-gen): remove field 'raw' from api-doc-file

- cmd/nirvana/api/api.go
We downgraded the swagger-ui version to 3.22.2 in #321, but after #326 we removed the `ExtraProps`, the problem is gone, so I'm gonna upgrade the swagger-ui version again.
Fixes #
Reference to #
/cc @hezhizhen @supereagle 
```release-note
NONE
```
> chore(*): bump swagger-ui version to v3.25.3

- utils/generators/swagger/generator.go
close #330 
Fixes #
Reference to #
/cc @hezhizhen @supereagle 
```release-note
NONE
```
> fix(api-docs): remove title in response schema

- cmd/nirvana/project/init.go
Synced the template content in the init command with [nirvana-template-project](https://github.com/caicloud/nirvana-template-project) repo, now we can generate a template project with `nirvana init`, eg:
```
nirvana init ~/iawia002/go/src/github.com/caicloud/test1
nirvana init ~/iawia002/go/src/github.com/caicloud/test1 --registry cargo.dev.caicloud.xyz/release --base-registry cargo.caicloud.xyz/library
```
After this change, the generated structure will be:
```
.                                   #
├── .golangci.yml                   #
├── go.mod                          #
├── Makefile                        #
├── OWNERS                          #
├── README.md                       #
├── apis                            # Store apidocs (swagger …
```
> refactor(*): update template content in the init command

- cmd/nirvana/project/init.go
Do not enable the `-race` flag in production, it will affect performance.
Fixes #
Reference to #
```release-note
NONE
```
> fix(template): enable race detection in tests only

- cmd/nirvana/project/init.go
- definition/definition.go
- nirvana.go
- service/method.go
- service/modifier.go
close #273 
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> feat(*): support Head method

- definition/definition.go
- examples/getting-started/any-method/main.go
- service/executor.go
- utils/api/definitions.go
- utils/generators/swagger/generator.go
close #343 
Fixes #
Reference to #
/cc @gaocegege @simon-cj @hezhizhen 
```release-note
NONE
```
> feat(*): support to register all methods for a Definition

- definition/definition.go
- examples/getting-started/file/main.go
- service/executor.go
- service/utils.go
- utils/api/definitions.go
- utils/generators/swagger/generator.go
fix #345
After this, you can set the `Optional` field of the parameter to true and handle the empty parameter situation yourself, eg:
```go
Parameters: []definition.Parameter{
{
Source:   definition.File,
Name:     "file",
Optional: true,
},
},
func Upload(ctx context.Context, file multipart.File) (string, error) {
if file == nil {
// do something
}
// do something else
}
```
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```
> feat(*): add a Optional field to the Parameter struct

- definition/helper.go
Add optional parameter for operators and there is no need to use a temporary variables to receive the additional operators.
Fixes #
Reference to #
/cc @
```release-note
NONE
```
> chore: add parameter for operators

- log/log.go
Both Kubernetes and our engineering guidelines recommend setting the value of the debug level to 4, so change the debug level in Nirvana to 4.
Reference to https://github.com/caicloud/engineering/blob/master/guidelines/golang.md#logging-1
/cc @supereagle @lichuan0620 
```release-note
NONE
```
> chore(*): update debug level from MaxInt32 to 4

- service/context.go
I have a demand is that analysis the response body in middleware，but I can't acquire it. I implement it by adding the function `ResponseBody`.
Fixes #
Reference to #
/cc @iawia002 
```release-note
NONE
```
> Feat(resp): add ResponseBody func to acquire resp body

- cmd/nirvana/api/api.go
- utils/generators/golang/generator.go
- utils/generators/golang/helper.go
- utils/generators/swagger/generator.go
- utils/generators/utils/definitions.go
- utils/project/config.go
Fix issue where the generated client does not import third-party packages properly, eg:
```go
import (
"go.mongodb.org/mongo-driver/bson/primitive"
)
type XXX struct {
ID primitive.ObjectID `json:"_id"`
}
```
Definition of `ObjectID`:
```go
type ObjectID [12]byte
```
For now, we will treat `ObjectID` as an array of bytes so we won't import the `go.mongodb.org/mongo-driver/bson/primitive` package, this PR fixes this issue and makes small adjustments to the formatting of the generated content.
Fixes #
Reference to #
```release-note
NONE
```
> fix(*): fix issue where generated client does not import third-party packages properly

- utils/generators/golang/generator.go
For Definitions that use the `Any` method, methods of the generated client requires manually passing in the method and corresponding response code parameter
before:
```go
func (c *Client) GetWorkload(ctx context.Context, type_ string) (workload *Workload, err error) {
workload = new(Workload)
err = c.rest.Request("Any", 200, "/apis/app/v1/workloads/{workload}").
Path("type", type_).
Data(workload).
Do(ctx)
return
}
```
after:
```go
func (c *Client) GetWorkload(ctx context.Context, method string, responseCode int, type_ string) (workload *Workload, err error) {
workload = new(Workload)
err = c.rest.Request(method, responseCode, "/apis/app/v1/workloads/{workload}").
Path("type", type_).
Data(workload).
Do(ctx)
return
}
```
**Which issue(s) this PR is …
> fix(*): support the any method in client generation

- utils/project/config.go
- utils/project/path.go
Make `nirvana api` work with go module.
Proof:
```
$ pwd
/Users/knight/github-caicloud/foo2
[20-10-26 14:31] [kind-kind] byted-mbp@ ~cchub/foo2
$ l
total 48K
drwxr-xr-x 2 knight staff   64 Oct 26 13:27 apis/
drwxr-xr-x 2 knight staff   64 Oct 26 13:27 bin/
drwxr-xr-x 3 knight staff   96 Oct 26 13:27 cmd/
drwxr-xr-x 3 knight staff   96 Oct 26 13:27 build/
drwxr-xr-x 3 knight staff   96 Oct 26 13:27 docs/
drwxr-xr-x 6 knight staff  192 Oct 26 13:27 hack/
drwxr-xr-x 8 knight staff  256 Oct 26 13:27 pkg/
drwxr-xr-x 3 knight staff   96 Oct 26 13:27 test/
-rw-r--r-- 1 knight staff  446 Oct 26 13:27 go.mod
-rw-r--r-- 1 knight staff  460 Oct 26 13:27 nirvana.yaml
-rw-r--r-- 1 knight staff  451 Oct 26 13:27 .golangci.yml
-rw-r--r-- 1 knight staff 5.7K Oct 26 …
```
> feat(cmd::api): work with go module

- utils/api/utils.go
Bump Swagger UI version to 3.36.0, example page:
Fixes #
Reference to #
/cc @xpofei 
```release-note
Bump Swagger UI version to 3.36.0.
```
> chore(*): bump Swagger UI version to 3.36.0

- cmd/nirvana/client/client.go
- utils/project/path.go
- utils/project/path_test.go
Continue #371, make `nirvana init/client` work with go module.
```console
$ nirvana init test2
INFO  1027-14:28:38.844+08 init.go:186 | Created project at /Users/bytedance/Downloads/test2
$ cat test2/go.mod
module test2
require (
github.com/caicloud/nirvana master
)
```
```console
$ nirvana client pkg
INFO  1027-14:33:44.066+08 client.go:83 | Project root directory is /Users/bytedance/Downloads/test2
INFO  1027-14:33:44.069+08 client.go:119 | Generated golang client package test2/client
```
Fixes #374
/cc @xpofei @knight42 
```release-note
Make `nirvana init/client` work with go module.
```
> feat(*): make init/client command work with go module

- nirvana.go
This blank import was incorrectly cleaned up in #372
Fixes #
Reference to #
/cc @xpofei 
```release-note
Add the missing blank import in nirvana.go
```
> fix(*): add the missing blank import in nirvana.go

- rest/rest.go
- rest/rest_test.go
perf(client): request support query in url
Fixes #
Reference to #
/cc @iawia002 
```release-note
Client request now supports query in url
```
> perf(client): request support query in url

- .github/workflows/ci.yml
update #384
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> chore(*): update GitHub Actions config

- definition/helper.go
- examples/api-basic/api/v2/app_test.go
- examples/getting-started/rpc-style/apis/api.app.v1.json
- examples/getting-started/rpc-style/apis/api.storage.v1alpha1.json
- examples/getting-started/rpc-style/main.go
- middlewares/metrics/metrics.go
- nirvana.go
- plugins/apidocs/apidocs.go
- plugins/healthcheck/healthz.go
- plugins/profiling/profiling.go
- plugins/version/version.go
- service/builder/builder.go
- service/rest/builder.go
- service/rpc/builder.go
- service/types.go
- utils/api/api.go
- utils/api/definitions.go
- utils/api/utils.go
- utils/builder/builder.go
- utils/unittest/unittest.go
Other plugins like metrics rely on configuring the middleware for the root path (/) to automatically configure the middleware for all paths which doesn't work for the RPC API style, which requires manual configuration of middleware and descriptor for the RPC style server.
Fixes #
Reference to #382 
/cc @xpofei 
```release-note
NONE
```
> feat(*): make multiple plugins support the RPC builder

- service/rpc/builder_test.go
Fixes #
Reference to #
```release-note
NONE
```
> test(rpc): add unit test for rpc style api

- definition/helper.go
- middlewares/metrics/metrics.go
Add `SimpleRPCDescriptor`
Fixes #
Reference to #
/cc @iawia002 
```release-note
NONE
```
> chore(*): add SimpleRPCDescriptor for convenience

- service/modfier_test.go
- service/modifier.go
The value of `ErrorProduces` field of `Definition` is the same as `Produces` field by default:
1. https://github.com/caicloud/nirvana/blob/b561a068104cef53a92bd475c326231132ec6158/service/rpc/builder.go#L129
2. https://github.com/caicloud/nirvana/blob/b561a068104cef53a92bd475c326231132ec6158/service/rest/builder.go#L157
Currently the modifier  `ProduceAllIfProducesIsEmpty` only modify the `Produces` field, so `ErrorProduces` would be empty If `Produces` is empty, then nirvana will throw an error when building executor:
https://github.com/caicloud/nirvana/blob/b561a068104cef53a92bd475c326231132ec6158/service/executor/executor.go#L59-L61
Fixes #
Reference to #
**Special notes …
> fix(*): make modifier ProduceAllIfProducesIsEmpty also modify ErrorProduces

- errors/errors.go
- service/handler.go
- service/utils.go
Fixes #
Reference to #
```release-note
NONE
```
> chore(*): expose several functions for external use

- utils/generators/golang/helper.go
Fixes #
Reference to #
/cc @xpofei @knight42 
```release-note
utils: fix an issue when the Auto parameter is a pointer in client generation.
```
> fix(utils): fix an issue when the Auto parameter is a pointer in client generation

- rest/rest.go
- utils/generators/golang/helper.go
- utils/generators/swagger/generator.go
Fixes #
Reference to #
```release-note
NONE
```
> fix(*): handle the custom Destination in API docs and client generation

- utils/generators/golang/helper.go
- utils/generators/golang/helper_test.go
Currently the aliases of foreign packages imported in the generated client code are non-deterministic, which leads to unnecessary changes of the generated client code.
For instance, let's say the client code imports `github.com/repo/apis/v1alpha1` and `github.com/repo/server/v1alpha1`, then the aliases could be
```
import (
v1alpha1 "github.com/repo/apis/v1alpha1"
v1alpha11 "github.com/repo/server/v1alpha1"
)
```
Or
```
import (
v1alpha11 "github.com/repo/apis/v1alpha1"
v1alpha1 "github.com/repo/server/v1alpha1"
)
```
And the client code would be changed slightly because of the different alias even if nothing actually changes.
This PR sorts the type names before parsing them to address this issue.
**Which issue(s) this PR is related to** *(optional, …
> fix(generator): sort type names to make the package aliases deterministic

- service/source.go
- utils/generators/swagger/generator.go
support 'required' tag for auto param, if defined an auto param like this:
type XXX {
ID  int64  `source:"query,Id,optional"`
}
'required' tip will now show in swagger
Fixes #
Reference to #
/cc @iawia002 
```release-note
Support 'required' tag for auto param
```
> feat(swagger): support 'optional' tag for auto param

- utils/generators/swagger/generator.go
type XXX {
ID int64 source:"query,Id,optional"
Name string source:"query,Name,default=bob"
}
neither of ID and Name 'required' tip will show in swagger
Fixes #
Reference to #
/cc @iawia002 
```release-note
'default' tag in param also mean optional
```
> feat(swagger): default tag in param also mean optional

- rest/rest.go
Fixes #
Reference to #
/cc @iawia002 
```release-note
Fix bug of query cache, now client cache will be deep copied after called Request
```
> fix(client): fix bug of query cache (#381)

- utils/generators/golang/helper.go
chore: add underscore to proposedName when it is equal with type or be literal
Fixes #
Reference to #
```release-note
NONE
```
> chore: add underscore to proposedName when it is equal with type or be literal

- errors/external.go
Fixes #
Reference to #
```release-note
NONE
```
> fix(*): handle TOP RPC style error data

- rest/rest.go
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> fix(rest): handle pointer value in the parameter

- cmd/nirvana/main.go
See previous discussions in https://github.com/caicloud/nirvana/pull/373#issuecomment-717156181, this is another simpler solution, users are able to get the version information no matter how they install nirvana.
```console
$ nirvana
Nirvana toolchains
Usage:
nirvana [command]
Available Commands:
api         Generate API documents for your project
client      Create client for project
help        Help about any command
init        Create a basic project structure
Flags:
-h, --help      help for nirvana
--version   version for nirvana
Use "nirvana [command] --help" for more information about a command.
$ nirvana --version
nirvana version v0.3.0-alpha.0
```
I'll manually update the version number when we are going to release a new version.
**Which …
> feat(cmd): add version information

- cmd/nirvana/main.go
Update version in the master branch, prepare for the next version.
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> chore(*): prepare for v0.4.0-alpha.1

- utils/generators/swagger/generator.go
- utils/project/config.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(*): support setting base path in API docs

- utils/generators/swagger/generator.go
We take the below struct for example:
```go
type T2 struct {
Name []string `json:"Name1"`
}
type T1 struct {
CC map[string]string `json:"CC"`
}
type Test struct {
T2 `json:",inline"`
T1 T1     `json:"T1"`
AA string `json:"AA"`
}
type T4 struct {
AA string `json:"AA"`
}
type T3 struct {
AA []string `json:"AA"`
T4 T4       `json:"T4"`
}
type Workload struct {
Test `json:",inline"`
Name string `json:"Name"`
T3   T3     `json:"T3"`
}
```
Before:
After:
Fixes #
Reference to #
/cc @xpofei 
```release-note
Handle inline struct in API docs generation.
```
> feat(*): handle inline struct in API docs generation

- cmd/nirvana/main.go
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> [release-0.3] chore(*): prepare for v0.3.1

- utils/generators/swagger/generator.go
continue #437 
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> fix(*): handle more inline situations in API docs generation

- utils/generators/swagger/generator.go
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> fix(*): ignore unexported fields in API docs generation

- cmd/nirvana/api/api.go
Reference to https://github.com/caicloud/nirvana/issues/448#issuecomment-764190777
/cc @xpofei 
```release-note
NONE
```
> chore(cmd): update default APIs path

- definition/definition.go
- definition/rpc.go
- service/rest/builder.go
- service/rpc/builder.go
- service/rpc/builder_test.go
- utils/api/definitions.go
- utils/generators/swagger/generator.go
Support add example in parameter, before:
After:
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> refactor(*): support add example in parameter

- utils/api/utils.go
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> chore(*): bump Swagger UI version to 3.40.0

- cmd/nirvana/buildutils/builder.go
- utils/generators/swagger/generator.go
- utils/project/config.go
Update the definitions of the `Host` and `Contact` fields in the configuration to sync with the [swagger specification](https://swagger.io/specification/)
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> refactor(*): update the Host and Contact field in the config

- utils/generators/swagger/generator.go
ref: #451
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```
> fix(*): fix the setting method of parameter example in API docs generation
