router/router.go

`Split` creates a useless empty string segment when there is nothing before char '{'. It's a bug.

fix(router): ignore empty string segment in splitting

---

.travis.yml
config.json
router/basic.go
router/regexp.go
router/router.go

add `gometalinter` to project
better code quality

feat(lint): add gometalinter

---

service/content.go
service/content_test.go
service/source.go
service/source_test.go
service/utils.go

Now, Type `string` and `[]byte` can be used to receive data from http body.
In some occasion, we just want get body string rather than a struct.
**Release note**
```release-note
Let consumers and producers support string and []byte.
```

feat(service): let consumers and producers support string and []byte

---

service/context.go

The canonical key for "accept-encoding" is "Accept-Encoding".
/assign @kdada 
```release-note
NONE
```

fix(context): canonical format of the MIME header key

---

errors/errors.go
errors/kinds.go
service/content.go

Support to marshal errors into XML. Standard XML package does not support map. Wrap the map and implement `MarshalXML`.
/assign @yejiayu 
/area framework
/kind bug
/priority p0
```release-note
NONE
```

fix(errors): support to marshal errors into XML

---

definition/helper.go
nirvana.go
service/executor.go
service/executor_test.go
service/modifier.go
service/utils.go

For an operator chain:
```
in -> operators[0].In()
operators[0].Out() -> operators[1].In()
...
operators[N].Out() -> out
```
Parameter types and result types are checked at startup time now.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #73 
/assign @yejiayu 
/assign @Jimexist 
/area framwork
/kind enhancement
/priority P1
```release-note
Check parameters and results of operators at startup time
```

feat(builder): validate operators at startup time

---

errors/errors.go
errors/errors_test.go
service/content.go

- Implement method Error for message
- Support plain error message for TextSerializer and OctetStreamSerializer
Fixes #128
```release-note
Support plain error message for TextSerializer and OctetStreamSerializer
```

feat(service): support plain error message for TextSerializer and OctetStreamSerializer

---

examples/instrumentation/main.go
plugins/metrics/metrics.go

Use milliseconds instead of microseconds
Fixes #
```release-note
NONE
```

fix(metrics): histogram should collect latencies for milliseconds 

---

service/builder.go
service/context.go

We have a cache pool for HTTP context before. It creates new context when a request coming and recycles it after the request done. But if someone use this context after it being recycled, it may panic. 
There are two ways we have considered:
1. Add a safe layer for the context
- Flexible
- Still has a problem about retained HTTPContext.
```go
func handler(ctx context.Context) {
// The retained httpCtx may go in wrong after the context being recycled.
httpCtx := service.HTTPContextFrom(ctx)
}
```
1. Remove cache pool
- Simple
- Has minimal performance loss (about 1%).
So we choose the second solution. 
/cc @ddysher 
/cc @walktall 
/cc @zoumo 
/cc @Jimexist 
```release-note
Remove …
```

fix(service): remove cache pool for http context

---

config/config.go
config/hooks.go

Add PreConfigure and PostConfigure hooks.
After creating nirvana server, config becomes immutable. So we need the two hooks.
Fixes #
/cc @zoumo 
```release-note
Add PreConfigure and PostConfigure hooks
```

feat(config): add PreConfigure and PostConfigure hooks

---

service/builder.go

Descriptor's Consumes and Produces can't impact its definitions.
Fixes #
/cc @yejiayu 
```release-note
NONE
```

fix(service): Consumes and Produces of descriptor should affect current definitions

---

definition/method/method.go
definition/method/method_test.go

In the past, `definition.Function` only support functions. With `method` package in this pr, you can get the power to make a method be like a function.
```go
// Before nirvana server starting
instance := InitSomeClass()
method.Put(instance)
// In definition:
{
...
Function: method.Get(&SomeClass{}, "SomeMethod"),
... 
}
```
Then you don't need to do this:
```go
func (* SomeClass) Definitions()[]definition.Definition {
return []definition.Definition {
...
Function: this.SomeMethod,
... 
}
}
``` 
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```

feat(method): support method in definition

---

log/std.go

This PR is for skipping err check:
```
$ gometalinter --config=config.json ./...
log/std.go:171:12:warning: error return value not checked (fmt.Fprint(l.stream, data)) (errcheck)
```
Fixes #
Reference to #
/cc @zjj2wry 
```release-note
NONE
```

fix(log): skip err check in std logger

---

cmd/nirvana/project/init.go

Fix a typo in the template.
```release-note
NONE
```

init.go: Fix a typo in template

---

rest/rest.go

correct resp should not return an err
```release-note
NONE
```

bugfix: correct resp should not return an err

---

utils/project/path.go
utils/project/path_test.go

nirvana init cmd report an error on windows as follow:  
> FATAL 0312-11:49:06.321+08 init.go:49 \| can't format go source file pkg/apis/v1/ descriptors/descriptors.go: 6:4: unknown escape sequence (and 2 more errors)  
this PR fixed it.
@kdada 
```release-note
fix: init cmd path error on windows.
```

fix: init cmd path error on windows.

---

plugins/metrics/metrics.go

The help of metrics request latencies summary present wrong unit.
None
/cc @kdada 
```release-note
NONE
```

fix: correct metrics help unit of the request latencies summary

---

service/context.go

It will not be calling `WriteHeader` when upgrade http to websocket. 
Nirvana always check `HeaderWritable` and call `WriteHeader` , this will cause the `net/http` output warning log.
Fixes #278 
/cc @kdada 
```release-note
NONE
```

fix(#278): prevent WriteHeader from automatically calling when hijack used

---

definition/helper.go
definition/helper_test.go

fix panic when use operator in DestinationHandler. example:
```
var getMessage = def.Definition{
Method:      def.Get,
Summary:     "Get Message",
Description: "Get a message by id",
Function:    message.GetMessage,
Parameters: []def.Parameter{
def.PathParameterFor("message", "Message id"),
},
Results: []def.Result{
{
Destination: def.Data,
Description: "",
},
{
Destination: def.Error,
Operators: []def.Operator{
def.OperatorFunc("Error", func(context.Context, string, error) (error, error) {
return nil, nil
}),
},
},
},
}
// GetMessage return a message by id.
func GetMessage(ctx context.Context, id int) (*Message, error) {
return &Message{
ID:      id,
Title:   "This is an example",
Content: "Example content",
}, nil
}
```
when access the url, the …

fix(operator): panic when call Operate with nil data

---

examples/getting-started/healthcheck/echo.go
plugins/healthcheck/healthz.go

Add a type parameter for the health check plugin to support different check types, such as readiness requires more check steps than liveness.
If this change makes sense, I'll update the document soon
Fixes #
Reference to #
/cc @kdada 
```release-note
NONE
```

feat(plugin): add a type parameter for the health check plugin

---

service/source.go

return the struct instance instead of the pointer of it will cause panic:
```
reflect: Call using service.repeatableCloserForFile as type multipart.File
```
Fixes #
Reference to #
/cc @kdada @hezhizhen 
```release-note
NONE
```

fix(service): fix a problem in the file parameter generator

---

plugins/metrics/metrics.go

This PR should be considered as a __breaking change__.
Refactored the metrics so that they meet the [K8 Instrumentation Guideline](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/instrumentation.md), the changes include:
1. Removed redundant labels.
2. Added a `component` label to all metrics; it takes the value of metric namespace.
3. Renamed according to the naming convention.
4. The Histogram type request duration metric use standard bucket sizes (which produce much more data, which will put more pressure on Prometheus, but is also more precise).
5. Changed the unit of the request duration metric from milliseconds to seconds.
As a result, the metrics should now look a lot like the APIServer request …

refactor(metrics): standardize Prometheus metrics

---

service/filter.go

Add a new filter to support setting `maxMemory` manually when parsing request form. For those who need to set a custom `maxMemory` value, you can use this filter to replace the original default one.
close #315 
/cc @hezhizhen 
```release-note
NONE
```

feat(service): add a new filter to support setting maxMemory manually when parsing request form

---

middlewares/reqlog/reqlog.go
middlewares/reqlog/reqlog_test.go

Added two middleware that mimick the functionality of the `reqlog` plugin. Unlike a plugin, with these middlewares, the user would be able to enable request log only for a subset of their descriptors.
Fixes #
Reference to #
/cc @iawia002 @supereagle 
```release-note
NONE
```

feat(middleware): implemented two reqlog middlewares

---

utils/generators/swagger/generator.go

For now, if we set a default value for a field of an auto parameter, the API docs generation will fail with the error below:
```
FATAL 0601-16:59:25.166+08 api.go:61 | json: error calling MarshalJSON for type spec.Swagger: json: error calling MarshalJSON for type *spec.Paths: json: error calling MarshalJSON for type spec.PathItem: json: error calling MarshalJSON for type *spec.Operation: json: error calling MarshalJSON for type spec.OperationProps: json: error calling MarshalJSON for type spec.Parameter: json: error calling MarshalJSON for type *swagger.rawJSON: invalid character 's' after top-level value
```
Fixes #
Reference to #272  …

fix(api-docs): handle the default value of parameter correctly

---

utils/generators/swagger/generator.go

If we have more than one rule, when the first mismatch occurs, the `path` will be set to empty, this will cause all subsequent rules to fail to match, fix #337
Fixes #
Reference to #
/cc @supereagle @moshuipan
```release-note
NONE
```

fix(*): fix path rule handling issue in the API docs generation

---

definition/definition.go
examples/getting-started/handler/main.go
hack/verify_boilerplate.py
service/builder.go
service/executor.go
service/utils.go
utils/api/definitions.go

This PR makes nirvana supports to add a http.Handler (e.g. httputil.ReverseProxy) directly to the router.
See examples/getting-started/handler for a real example.
close #339 
/cc @gaocegege 
```release-note
NONE
```

feat(*): support to add a http.Handler directly to the router

---

cmd/nirvana/api/api.go
definition/helper.go
examples/api-basic/main.go
examples/api-basic/nirvana.yaml
nirvana.go
service/builder.go
service/content.go
utils/api/utils.go
utils/generators/swagger/generator.go
utils/generators/utils/utils.go

Support serving API documentation pages when the server starts, take `examples/api-basic` project as an example:
```
INFO  1023-18:11:50.982+08 config.go:309 | Listening on :8080
INFO  1023-18:11:52.009+08 builder.go:240 | Definitions: 1 Middlewares: 0 Path: /docs/api.v2.json
INFO  1023-18:11:52.009+08 builder.go:255 |   Method: Get Consumes: [] Produces: [application/json]
INFO  1023-18:11:52.009+08 builder.go:240 | Definitions: 1 Middlewares: 0 Path: /docs/api.v1.json
INFO  1023-18:11:52.009+08 builder.go:255 |   Method: Get Consumes: [] Produces: [application/json]
INFO  1023-18:11:52.009+08 builder.go:240 | Definitions: 1 Middlewares: 0 Path: /docs
INFO  1023-18:11:52.009+08 builder.go:255 |   Method: Get Consumes: [] Produces: [text/html]
INFO …
```

feat(*): support serving API documentation pages when the server starts

---

definition/rpc.go
service/rpc/builder.go

Use the `Name` field instead of `Summary` directly
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```

fix(*): remove the Summary field in RPCAction struct

---

utils/generators/golang/helper.go

后计数会导致 names 统计了增加了数字的 name 而非原本的值，比如我有三个 configMap 同名参数，现在的逻辑会导致计数中出现 configMap 和 configMap1 的 key，第三个 configMap 会被错误地转换为 configMap1 而非 configMap2
Fixes #
Reference to #
/cc @hezhizhen 
```release-note
NONE
```

fix(utils): fix the counting logic of duplicate names

---

service/rpc/builder.go
service/rpc/builder_test.go

Prevent users from setting duplicated RRC path by mistake.
Fixes #
Reference to #
/cc @iawia002 
```release-note
NONE
```

fix(rpc): disallow duplicated rpc path

---

config/center.go

In the current design, if we start more than one server at the same time, eg:
```
cmd := config.NewNamedNirvanaCommand("server1", &config.Option{Port: 7070})
cmd2 := config.NewNamedNirvanaCommand("server2", &config.Option{Port: 7071})
go cmd.Execute(echo)
go cmd2.Execute(echo)
<-stopCh
```
This has the probability of causing the `concurrent map writes` error in the `Set` method
Fixes #
Reference to #
/cc @xpofei 
```release-note
NONE
```

fix(config): add lock in Set function to avoid concurrent map writes when we run several servers at once

---

utils/api/definitions.go
utils/api/definitions_test.go

目前如果 parameters 的个数比函数的参数个数多，或者 results 的个数比函数的返回值的个数多的话，那么在执行 `nirvana api` 或 `nirvana client` 的时候 nirvana 就会 panic:
```
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/caicloud/nirvana/utils/api.NewDefinition(0xc00d6038f0, 0xc00022b8f8, 0x157a5e4, 0x3, 0xc005401f00, 0x0, 0x0)
/Users/knight/go/pkg/mod/github.com/caicloud/nirvana@v0.3.0-rc.3/utils/api/definitions.go:147 +0xe25
github.com/caicloud/nirvana/utils/api.NewDefinitions(0xc00d6038f0, 0xc000164b40, 0x1, 0x1, 0x157a5e4, 0x3, 0xc005401b00, 0x1, 0x1, 0x0, ...)
/Users/knight/go/pkg/mod/github.com/caicloud/nirvana@v0.3.0-rc.3/utils/api/definitions.go:175 +0x148
github.com/caicloud/nirvana/utils/api.NewPathDefinitions(0xc00d6038f0, 0xc00d603950, …
```

fix(utils): 确保 params 跟 results 的个数与函数的参数及返回值的个数相同

---

utils/generators/golang/helper.go

修复在生成 API 或者 client 的时候如果某个结构体定义里包含自身字段会无限循环的 bug
Fixes #
Reference to #
```release-note
NONE
```

fix(pkg): ignore the invoke when the struct container the field which has the same type with itself

---

utils/generators/golang/helper.go

`token.Lookup(name).IsLiteral()` cannot be used to determine if a string is a built-in type.
Fixes #
Reference to #425 
/cc @xpofei @whalecold 
```release-note
NONE
```

fix(*): determine if a string is a built-in type

---

utils/api/comments.go
utils/generators/golang/generator.go
utils/generators/golang/helper.go

Previously, generating a client copies all the built-in types, this PR changes the processing method to directly import the corresponding types to solve the type duplication problem and speed up the client generation speed.
The effect is as follows:
```diff
diff --git a/pkg/server/client/v20201010/client.go b/pkg/server/client/v20201010/client.go
index 8779df2..adbb782 100644
--- a/pkg/server/client/v20201010/client.go
+++ b/pkg/server/client/v20201010/client.go
@@ -2,6 +2,9 @@ package v20201010
import (
"context"
+	addon "github.com/caicloud/module-template/pkg/server/apis/addon"
+	app "github.com/caicloud/module-template/pkg/server/apis/app"
+	storage "github.com/caicloud/module-template/pkg/server/apis/storage"
rest …
```

refactor(*): import API types directly in client generation, no longer copy
